// <auto-generated />
using System;
using InitProject.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InitProject.Migrations;

[DbContext(typeof(Data.Context.DbPgContext))]
[Migration("20230417183018_pgTeste")]
partial class pgTeste
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Proxies:ChangeTracking", false)
            .HasAnnotation("Proxies:CheckEquality", false)
            .HasAnnotation("Proxies:LazyLoading", true)
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("InitProject.Model.Entities.EpisodeEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AnimeId")
                    .HasColumnType("integer");

                b.Property<int>("Duracao")
                    .HasColumnType("integer");

                b.Property<int>("Numero")
                    .HasColumnType("integer");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("AnimeId")
                    .IsUnique();

                b.ToTable("Episodes");
            });

        modelBuilder.Entity("InitProject.Model.Models.AnimeEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("AnoLancamento")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Genero")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Animes");
            });

        modelBuilder.Entity("InitProject.Model.Entities.EpisodeEntity", b =>
            {
                b.HasOne("InitProject.Model.Models.AnimeEntity", "Anime")
                    .WithOne("Episode")
                    .HasForeignKey("InitProject.Model.Entities.EpisodeEntity", "AnimeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Anime");
            });

        modelBuilder.Entity("InitProject.Model.Models.AnimeEntity", b =>
            {
                b.Navigation("Episode")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
